name: Automated Build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  automated-build:
    uses: b-abadie/test/.github/workflows/automated-build.yaml@main
    secrets:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
    with:
      DOCKER_HUB_USERNAME: enixsas
